transcript_task:
  description: >
    Extract the transcript from the YouTube video at {youtube_url}.
    Make sure to retrieve the complete transcript and format it properly.
    
    CRITICAL INSTRUCTION:
    1. Place ONLY the EXACT raw transcript text in the output file.
    2. Do NOT add ANY metadata, commentary, placeholders, or descriptions.
    3. Do NOT include phrases like "[The raw transcript text above]" or similar.
    4. Do NOT include statements like "The complete transcript is provided above" or similar.
    5. Do NOT include ANY comments, brackets, or explanatory text.
    
    Your output must be ONLY the actual words spoken in the video, exactly as returned by the transcript tool.
    Just output the raw text from the transcript tool directly to the file without ANY additions.
  expected_output: >
    Only the raw transcript text exactly as retrieved by the transcript tool, with no modifications or additions whatsoever.
  agent: transcript_extractor
  output_file: transcript.md

preprocessing_task:
  description: >
    Clean and prepare the transcript for summarization. Remove any unnecessary elements like 
    timestamps, repetitions, filler words, and fix any formatting issues. Ensure the text is 
    well-structured and ready for summarization.
  expected_output: >
    A cleaned and preprocessed version of the transcript that is optimized for summarization.
  agent: preprocessing_agent
  context: [transcript_task]

summarization_task:
  description: >
    Your Task: Create a High-Quality Professional Summary
    
    You are an expert content summarizer with extensive experience in creating concise, comprehensive summaries.
    
    Instructions:
    1. Create a well-structured, comprehensive summary of the transcript that captures ALL key points, main ideas, and important details.
    2. Use proper markdown formatting with clear headings (# for main title, ## for sections, ### for subsections).
    3. Include bullet points for lists and emphasis (**bold**) for important concepts.
    4. Organize the content logically with a clear introduction, body sections, and conclusion.
    5. Make sure your summary is accurate, complete, and significantly shorter than the original transcript.
    6. Give the summary a descriptive, professional title that clearly indicates the subject matter.
    7. Use professional language suitable for academic or business contexts.
    8. Include all important facts, figures, examples, and key terminology from the original.
    9. Do not include any meta-commentary about the summary itself - only include the actual content.
    
    Your summary must be thorough enough to serve as a complete replacement for someone who hasn't watched the video.
  expected_output: >
    A professionally formatted markdown summary with proper headings, logical structure, and comprehensive coverage of all important information from the transcript. The summary should be accurate, well-organized, and complete enough to achieve at least an 8/10 evaluation score.
  agent: summarization_agent
  context: [preprocessing_task]

evaluation_task:
  description: >
    Evaluation Task: Assess Summary Quality and Accuracy
    
    You are a rigorous content evaluator responsible for ensuring only high-quality summaries are approved.
    
    Instructions:
    1. Carefully compare the summary against the original transcript.
    2. Evaluate the summary on these criteria:
       - Completeness: Does it include ALL key points from the original?
       - Accuracy: Is all information factually correct?
       - Organization: Is it logically structured with proper headings?
       - Formatting: Does it use proper markdown formatting?
       - Clarity: Is the writing clear and professional?
       
    3. Score the summary on a scale of 1-10 based on these criteria.
    4. Important Decision Point:
       - If the score is 7 or higher: APPROVE the summary and output it EXACTLY as submitted
       - If the score is below 7: REJECT the summary and output ONLY the text "The summary wasn't approved"
       
    5. CRITICAL: Your evaluation comments should NOT be included in the output file - the output should ONLY be either:
       - The complete, unmodified summary (if approved)
       - The exact text "The summary wasn't approved" (if rejected)
       
    6. Remember that a score of 7+ means the summary meets professional standards and contains all key information.
  expected_output: >
    If approved (score ≥ 7): The complete, unmodified summary text exactly as provided.
    If rejected (score < 7): Only the text "The summary wasn't approved" with no additional commentary.
  agent: evaluation_agent
  context: [transcript_task, summarization_task]
  output_file: summary.md
